<?= $this->doctype(); ?>
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->
<head>
    <meta charset="utf-8" />
    <?= $this->headTitle('API. Documentation')->setSeparator(' - ')->setAutoEscape(false) ?>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1" name="viewport" />

    <link href="/css/admin/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
    <link href="/css/admin/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
    <link href="/css/admin/redoc.css" rel="stylesheet" type="text/css"/>

    <link rel="shortcut icon" type="image/png" href="/favicon.png" />

    <?= $this->headLink(); ?>

</head>
<body>

<?= $this->renderChildModel('top-panel'); ?>

<div class="content-wrapper">
    <?= $this->content; ?>
</div>

<script src="/js/admin/lib/jQuery/jQuery-2.2.0.min.js"></script>
<script src="/css/admin/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
<script src="https://rebilly.github.io/ReDoc/releases/latest/redoc.min.js"> </script>

<?= $this->headScript(); ?>
<?= $this->inlineScript(); ?>

</body>
</html>