<?= $this->doctype(); ?>
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->
<head>
    <meta charset="utf-8" />
    <?= $this->headTitle('API. Documentation')->setSeparator(' - ')->setAutoEscape(false); ?>

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1" name="viewport" />

    <?= $this->headMeta(); ?>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <?php $this->headLink([
        'rel' => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/favicon.ico'
    ])
        ->prependStylesheet($this->basePath() . '/css/redoc.css')
        ->prependStylesheet($this->basePath() . '/plugins/bootstrap/dist/css/bootstrap.min.css'); ?>

    <?= $this->headLink(); ?>
</head>
<body>

<?= $this->renderChildModel('top-panel'); ?>

<div class="content-wrapper">
    <?= $this->content; ?>
</div>

<script src="https://rebilly.github.io/ReDoc/releases/latest/redoc.min.js"> </script>

<?php $this->headScript()
    ->prependFile($this->basePath() . '/plugins/bootstrap/dist/js/bootstrap.min.js')
    ->prependFile($this->basePath() . '/plugins/jquery/dist/jquery.min.js'); ?>

<?= $this->headScript(); ?>
<?= $this->inlineScript(); ?>

</body>
</html>